version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest # TODO replace latest by image version
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"

  app:
    build:
      context: .
    container_name: my_app
    ports:
      - "8080:8080"
