global:
  scrape_interval: 5s  # How often to scrape targets by default.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  # Prometheus itself as a target.
      
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "my_app"
    static_configs:
      - targets: [ "my_app:8080" ]

